### PR TITLE
Updated engine.py 

### PR DESCRIPTION
**Pull request by abhijithrajan**
Pandeia currently ignores PA information which causes errors when using either of the bar coronagraphs on NIRCam. Added a new function to correctly calculate the position of the requested companion.

### CODE REVIEW

**Comment by mperrin** [comment]
Hmm, something is screwy with this PR because it shows the entire contents of engine.py getting replaced rather than just a portion being edited.  

It looks like the file encoding may have gotten changed  - see https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not

**Comment by mperrin** [comment]
You probably need to change the file encoding locally and recommit that file. Try asking on ST Slack git channel if you get stuck

**Comment by abhijithrajan** [comment]
Somehow line ending changed from Unix to Windows. I've made the changes and it appears to be working now.

**Comment by mperrin** [comment]
Great, that looks better. But now  there are merge conflicts, probably because I just merged that other PR you reminded me about. You will probably need to git pull that and then fix the merge conflict I think.

**Comment by abhijithrajan** [comment]
Added in your commits and a diff on my machine now shows just the added function. Hopefully we can merge the two now.

**Comment by abhijithrajan** [comment]
Hi @mperrin @kjbrooks, I think the updates are now ready to be ingested.

**Comment by mperrin** [comment]
Hmm, github is still showing a branch conflict though...

**Comment by abhijithrajan** [comment]
I don't actually understand the conflict. Those are the parts of the code that we are trying to update.

**Pull request closed without merging**
